version: '3'

services:
  DataScraper:
    build:
      context: ./DataScraper
      dockerfile: ./DataScraper/Dockerfile_DataScraper

  WebGui:
    build:
      context: ./WebGui
      dockerfile: ./WebGui/Dockerfile_webgui
