version: '3'

services:
  data-scraper:
    build:
      context: ./DataScraper
      dockerfile: ./DOCKERFILE

  web-gui:
    build:
      context: ./WebGui
      dockerfile: ./DOCKERFILE
    ports:
      - '80:5000'
  
  # database:
  #   image: 'mariadb:10.3'
  #   container_name: database
  #   restart: always
  #   environment:
  #     - MYSQL_USER: user
  #     - MYSQL_PASSWORD: mypassword
  #     - MYSQL_DATABASE: my_database
  #     - MYSQL_ROOT_PASSWORD: rootpassword
    
  #   ports:
  #       - '3306:3306'
  #   volumes:
  #       - ${PWD}/mariadb/:/var/lib/mysql/
