version: '3'

services:
  data-scraper:
    build:
      context: ./DataScraper
      dockerfile: ./DOCKERFILE
    privileged: true 
    volumes:
      - /run/dbus:/run/dbus:ro

  web-gui:
    build:
      context: ./WebGui
      dockerfile: ./DOCKERFILE
    ports:
      - '8080:5000'
    
  
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  data: