hst : "host" {
    PythonSRV : "Stack Python" {
        DB :"SQLite DB" {
            icon : https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FAzure%20Database%20for%20MariaDB%20servers.svg
        }
        Scrp : "DataScrapper" {
            icon : https://icons.terrastruct.com/dev%2Fpython.svg
            explaination : |md   
                used to scrap data from bluetooth
            |

        }
        web : "WebGui" {
            icon : https://icons.terrastruct.com/dev%2Fpython.svg
            explaination : |md 
            used to display data from DB
            |
        }
    }
    blt : "Bluetooth hardware" {
        icon : https://icons.terrastruct.com/essentials%2F317-bluetooth.svg
    }
}
sens : "Weather Sensor" {}
PC : "User browser"{
    icon : https://icons.terrastruct.com/essentials%2F365-user.svg

}
hst.PythonSRV.DB <-- hst.PythonSRV.Scrp : "Write \ndata" {
    style : {
        stroke-dash: 5
        animated: true
        stroke : green
    }
}

hst.PythonSRV.DB --> hst.PythonSRV.web : "Read \nData" {
    style : {
        stroke-dash: 5
        animated: true
        stroke : green
    }
}

sens --> hst.blt --> hst.PythonSRV.scrp : "Read \nData" {
    style : {
        stroke-dash: 5
        animated: true
    }
}
hst.PythonSRV.web --> pc : "display \ndata"  {
    style : {
        stroke-dash: 5
        animated: true
        stroke : green
   
    }
}
hst.PythonSRV.web <-- pc : "write \nsettings" {
    style : {
        stroke-dash: 5
        animated: true
        stroke : orange
    }
}

hst.PythonSRV.DB <-- hst.PythonSRV.web : "write \nsettings" {
    style : {
        stroke-dash: 5
        animated: true
        stroke : orange
    }
}

hst.PythonSRV.DB --> hst.PythonSRV.Scrp : "Read \nsettings" {
    style : {
        stroke-dash: 5
        animated: true
        stroke : orange 
    }
}