# Use the official Python image as a base image
FROM python:3.11-bullseye

# Set the working directory in the container
WORKDIR /app

# Copy the script1.py and any other necessary files
COPY ./main.py /app/

# Install any dependencies
RUN apt-get update && apt-get install -y \
    bluez \
    dbus

RUN pip3 install --no-cache-dir bluepy

# Set the entry point
CMD ["python", "main.py"]