FROM resin/rpi-raspbian:jessie


# Set the working directory in the container
WORKDIR /app

# Copy the script1.py and any other necessary files
COPY ./main.py /app/

# Install any dependencies
RUN apt-get update && \
    apt-get install -y \
      build-essential  \
      python-dev python-pip \
      libglib2.0-dev libboost-python-dev libboost-thread-dev libbluetooth-dev && \
    pip install bleak

# Set the entry point
COPY entrypoint.sh .
CMD ./entrypoint.sh