# Use the official Python image as a base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the script1.py and any other necessary files
COPY ./main.py /app/

# Install any dependencies
RUN pip install --no-cache-dir bluepy

# Set the entry point
CMD ["python", "main.py"]