# Use the official Python image as a base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the script1.py and any other necessary files
COPY ./Helloworld.py /app/

#expose port
EXPOSE 5000

# Install any dependencies
RUN pip install --no-cache-dir flask

# Set the entry point
CMD ["python", "Helloworld.py"]
